name: CI Build and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: |
        dotnet build src/TestUpdaterAnalyzers/TestUpdaterAnalyzers.csproj -c Debug
        dotnet build src/TestUpdaterAnalyzers.Test/TestUpdaterAnalyzers.Test.csproj -c Debug
        dotnet build src/NXunitConverterAnalyzer/NXunitConverterAnalyzer.csproj -c Debug
        dotnet build src/NXunitConverterAnalyzer.Test/NXunitConverterAnalyzer.Test.csproj -c Debug
    - name: Test
      run: |
        dotnet test src/TestUpdaterAnalyzers.Test/TestUpdaterAnalyzers.Test.csproj
        dotnet test src/NXunitConverterAnalyzer.Test/NXunitConverterAnalyzer.Test.csproj
